### PR TITLE
Add Battery and Brightness features

### LINKED ISSUE #61: [Feature Request] Battery Percentage
It would be great for the battery status to be shown on the lock screen with your WebKit greeter.

### PR DESCRIPTION
**Pull request by JezerM**
Fixes #61

## Changes

- Added `Additions` component for Battery and Brightness features from web-greeter/nody-greeter.
    * Contains Battery and Brightness levels, auto-updated with `lightdm.battery_update` and `lightdm.brightness_update` signals.
    * Wrapped `Additions` and `Clock` inside a `div#top-container`. 
- Added battery and brightness icons from Material icons.
- Added battery and brightness properties for `src/lightdm.js` in debug mode.

## Preview

Imagen 3-7-22 a las 01 11

Imagen 3-7-22 a las 01 11

### CODE REVIEW

**Comment by moriel5** [comment]
That looks awesome!

Would it be possible to change the brightness, with either this or a follow-up pull request?

**Comment by JezerM** [comment]
You can do it if you have a proper and compatible display (like a laptop one). If there's a device inside `/sys/class/backlight/`, it will be detected by web-greeter/nody-greeter and so you could modify it with the brightness up/down keys.

However, a slider could be added in this PR as an extra~

**Comment by moriel5** [comment]
That's great.

I was only hoping for keyboard control on devices such as laptops, but adding a slider will make things even better (now we need to look at volume control).

I really need to find time to try compiling the Litarvan theme on Solus (and then to try packaging it, and requesting for it to officially be added to the Solus repos).

**Comment by JezerM** [comment]
> ... now we need to look at volume control.

I thought about it back then, but I think is worthless. Usually, you don't have sounds in your login or lock screen, and I'm almost 100% sure that no lightdm-webkit2-greeter theme has sounds.

Even if you're using a web based greeter as a Lock Screen with `light-locker`, the moment you lock the screen all media is paused/stopped, so it's not useful for volume control of your playlist either...

**Comment by moriel5** [comment]
Hmm... That is a valid point. I was thinking about feature parity with other OSs (Windows, MacOS) and display managers/greeters (gdm), however that would be an issue.

**Comment by JezerM** [comment]
Brightness slider added :D The slider appears when hovering the Brightness addition.

Here is a preview:

Imagen 3-7-22 a las 19 07

Imagen 3-7-22 a las 19 07

**Pull request merged**
